ms-user:
  url: http://localhost:8082

server:
  port: 8082 # MS-USER üçün port

spring:
  application:
    name: ms-user # Tətbiq adı kiçik hərflərlə olmalıdır
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # Verilənlər bazası URL-i
    username: postgres
    password: Ali200aa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Hibernate-in avtomatik sxem yeniləməsi
    show-sql: true # SQL sorğularını göstərmək üçün
    properties:
      hibernate:
        format_sql: true # SQL-in formatlanması
  main:
    allow-bean-definition-overriding: true # Ehtiyac varsa bean yenidən müəyyən edilməsini icazə verir

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server ünvanı
    fetch-registry: true # Başqa xidmətləri qeydiyyatdan keçir
    register-with-eureka: true # Özünü qeydiyyatdan keçirir
  instance:
    prefer-ip-address: true # IP ilə əlaqə üstünlük verir
